title: Cracking the tech interview
description: Cracking the tech interview, answer easily the technical questions
theme: just-the-docs

baseurl: "/cracking-the-tech-interview" # the subpath of your site, e.g. /blog
url: https://ftuyama.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
